{
    'name': 'Grant Management',
    'version': '17.0.8.0.0',
    'summary': 'Gestió de subvencions i ajuts — arquitectura extensible multi-finançador',
    'description': """
        Mòdul per a la gestió integral de subvencions: sol·licitud, reformulació,
        execució i justificació. Suporta múltiples finançadors (Ajuntament BCN,
        Diputació BCN, Generalitat DS, COSIFE, SMPRAV) sense canvis de codi.
    """,
    'author': 'grant_management',
    'category': 'Project',
    'license': 'LGPL-3',
    'depends': ['base', 'account', 'mail'],
    'data': [
        'security/grant_security.xml',
        'security/ir.model.access.csv',
        'data/grant_budget_category_data.xml',
        'data/grant_funder_data.xml',
        'data/grant_penal_center_data.xml',
        'data/grant_automation_data.xml',
        'views/config_views.xml',
        'views/grant_project_views.xml',
        'views/application_views.xml',
        'views/lifecycle_views.xml',
        'views/indicator_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'report/report_ajuntament_bcn.xml',
        'report/report_diputacio_bcn.xml',
        'report/report_smprav.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
