{
    'name': 'ACATHI Avaluació',
    'version': '17.0.1.1.0',
    'category': 'Social',
    'summary': "Instruments d'avaluació psicosocial i legal per a persones ateses",
    'author': 'ACATHI',
    'website': 'https://www.acathi.org',
    'license': 'LGPL-3',
    'depends': ['acathi_social', 'web'],
    'data': [
        'security/acathi_assessment_security.xml',
        'security/ir.model.access.csv',
        'data/acathi_assessment_cron.xml',
        'views/acathi_phq9_views.xml',
        'views/acathi_gad7_views.xml',
        'views/acathi_pcl5_views.xml',
        'views/acathi_hscl25_views.xml',
        'views/acathi_iesr_views.xml',
        'views/acathi_whodas_views.xml',
        'views/acathi_trafficking_views.xml',
        'views/acathi_assessment_session_views.xml',
        'views/acathi_assessment_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
